name: Rust CI
on:
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]

env: 
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup component add clippy --toolchain ${{ matrix.toolchain }}
      - name: Build
        run: cargo build --verbose
      - name: Test 
        run: cargo test --verbose
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings